package org.vt.ece4564.finalserver;

public class GUI extends javax.swing.JFrame
{
    public static int WIDTH_ = 600;
    public static int HEIGHT_ = 700;
    
    
    public GUI(){
        initComponents();
        
        this.setSize(WIDTH_, HEIGHT_);
        this.setResizable(false);
        
        // configure and start the server
        new ServerInitializer(HomeTextArea, message_log_, CtrlDebugTable);
        
        // set the text area not editable
        message_log_.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primary_jpanel_ = new javax.swing.JPanel();
        CtrlDebugPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        HomeTextArea = new javax.swing.JTextArea();
        CtrlDebugPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CtrlDebugTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message_log_ = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        primary_jpanel_.setPreferredSize(new java.awt.Dimension(600, 700));

        CtrlDebugPane.setMaximumSize(new java.awt.Dimension(600, 700));
        CtrlDebugPane.setMinimumSize(new java.awt.Dimension(600, 700));
        CtrlDebugPane.setPreferredSize(new java.awt.Dimension(550, 650));

        jPanel2.setPreferredSize(new java.awt.Dimension(584, 600));

        HomeTextArea.setEditable(false);
        HomeTextArea.setColumns(20);
        HomeTextArea.setLineWrap(true);
        HomeTextArea.setRows(5);
        HomeTextArea.setWrapStyleWord(true);
        HomeTextArea.setMaximumSize(new java.awt.Dimension(500, 600));
        jScrollPane3.setViewportView(HomeTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );

        CtrlDebugPane.addTab("Home", jPanel2);

        CtrlDebugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "X ", "Y", "Z"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(CtrlDebugTable);
        CtrlDebugTable.getColumnModel().getColumn(0).setResizable(false);
        CtrlDebugTable.getColumnModel().getColumn(1).setResizable(false);
        CtrlDebugTable.getColumnModel().getColumn(2).setResizable(false);
        CtrlDebugTable.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout CtrlDebugPanelLayout = new javax.swing.GroupLayout(CtrlDebugPanel);
        CtrlDebugPanel.setLayout(CtrlDebugPanelLayout);
        CtrlDebugPanelLayout.setHorizontalGroup(
            CtrlDebugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CtrlDebugPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        CtrlDebugPanelLayout.setVerticalGroup(
            CtrlDebugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CtrlDebugPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        CtrlDebugPane.addTab("CtrlDebug", CtrlDebugPanel);

        jPanel1.setPreferredSize(new java.awt.Dimension(592, 13));

        message_log_.setColumns(20);
        message_log_.setRows(5);
        message_log_.setFocusable(false);
        jScrollPane1.setViewportView(message_log_);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );

        CtrlDebugPane.addTab("Log", jPanel1);

        javax.swing.GroupLayout primary_jpanel_Layout = new javax.swing.GroupLayout(primary_jpanel_);
        primary_jpanel_.setLayout(primary_jpanel_Layout);
        primary_jpanel_Layout.setHorizontalGroup(
            primary_jpanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primary_jpanel_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CtrlDebugPane, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        primary_jpanel_Layout.setVerticalGroup(
            primary_jpanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primary_jpanel_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CtrlDebugPane, javax.swing.GroupLayout.PREFERRED_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primary_jpanel_, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primary_jpanel_, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                //System.out.println("running");
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CtrlDebugPane;
    private javax.swing.JPanel CtrlDebugPanel;
    private javax.swing.JTable CtrlDebugTable;
    private javax.swing.JTextArea HomeTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea message_log_;
    private javax.swing.JPanel primary_jpanel_;
    // End of variables declaration//GEN-END:variables

    //========================================================================//
    //============================Helper Functions============================//
}
